export const AGENT_BADGES: Record<string, { label: string; color: string }> = {
  'claude-code':   { label: 'CC', color: 'text-[#a371f7] bg-[#a371f7]/10 border-[#a371f7]/20' },
  'codex':         { label: 'CX', color: 'text-[#10a37f] bg-[#10a37f]/10 border-[#10a37f]/20' },
  'opencode':      { label: 'OC', color: 'text-[#f0883e] bg-[#f0883e]/10 border-[#f0883e]/20' },
  'mistral-vibe':  { label: 'MV', color: 'text-[#ff6f3c] bg-[#ff6f3c]/10 border-[#ff6f3c]/20' },
  'cline':         { label: 'CL', color: 'text-[#79c0ff] bg-[#79c0ff]/10 border-[#79c0ff]/20' },
};

export const DRIFT_COLORS: Record<string, string> = {
  green: '#00e676',
  yellow: '#ffb300',
  orange: '#ff9100',
  red: '#ff3d57',
};

export const EVENT_ICONS: Record<string, string> = {
  tool_call_pending: '⚡',
  tool_call_approved: '✅',
  tool_call_denied: '❌',
  tool_call_delegated: '⏭',
  tool_call_completed: '✓',
  tool_call_failed: '✗',
  permission_request: '🔐',
  user_prompt: '💬',
  agent_response: '🤖',
  agent_stop: '—',
  session_start: '🟢',
  session_end: '⬜',
  notification: '🔔',
  subagent_start: '🔀',
  subagent_stop: '🔀',
  stop_failure: '⚠',
  pre_compact: '📦',
  post_compact: '📦',
  elicitation: '📋',
  elicitation_result: '📋',
  analysis_result: '🔍',
  drift_check: '📐',
  drift_alert: '🚨',
};

export const BORDER_COLORS: Record<string, string> = {
  tool_call_pending: 'border-l-[#d29922]',
  tool_call_approved: 'border-l-[#3fb950]',
  tool_call_denied: 'border-l-[#f85149]',
  tool_call_delegated: 'border-l-[#8b949e]',
  tool_call_completed: 'border-l-[#3fb950]/50',
  tool_call_failed: 'border-l-[#f85149]',
  permission_request: 'border-l-[#d29922]',
  user_prompt: 'border-l-[#58a6ff]',
  agent_response: 'border-l-[#3fb950]/50',
  agent_stop: 'border-l-[#30363d]',
  session_start: 'border-l-[#3fb950]',
  session_end: 'border-l-[#30363d]',
  notification: 'border-l-[#58a6ff]',
  subagent_start: 'border-l-[#58a6ff]',
  subagent_stop: 'border-l-[#8b949e]',
  stop_failure: 'border-l-[#f85149]',
  pre_compact: 'border-l-[#8b949e]',
  post_compact: 'border-l-[#8b949e]',
  elicitation: 'border-l-[#58a6ff]',
  elicitation_result: 'border-l-[#58a6ff]',
  analysis_result: 'border-l-[#8b949e]',
  drift_check: 'border-l-[#d29922]',
  drift_alert: 'border-l-[#f85149]',
};

/** Raw hex colors for flowchart node borders (same palette as BORDER_COLORS but as hex values) */
export const NODE_BORDER_COLORS: Record<string, string> = {
  tool_call_pending: '#d29922',
  tool_call_approved: '#3fb950',
  tool_call_denied: '#f85149',
  tool_call_delegated: '#8b949e',
  tool_call_completed: '#3fb95080',
  tool_call_failed: '#f85149',
  permission_request: '#d29922',
  user_prompt: '#58a6ff',
  agent_response: '#3fb95080',
  agent_stop: '#30363d',
  session_start: '#3fb950',
  session_end: '#30363d',
  notification: '#58a6ff',
  subagent_start: '#58a6ff',
  subagent_stop: '#8b949e',
  stop_failure: '#f85149',
  pre_compact: '#8b949e',
  post_compact: '#8b949e',
  elicitation: '#58a6ff',
  elicitation_result: '#58a6ff',
  analysis_result: '#8b949e',
  drift_check: '#d29922',
  drift_alert: '#f85149',
};
